# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-20 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='txnetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=32, verbose_name='\u65f6\u95f4')),
                ('username', models.CharField(max_length=32, verbose_name='\u7528\u6237')),
                ('ip', models.GenericIPAddressField(db_index=True, null=True, protocol='ipv4', verbose_name='IP\u5730\u5740')),
                ('active', models.TextField(verbose_name='\u5237\u65b0\u5185\u5bb9')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u540c\u5fc3\u4e07\u70b9',
                'verbose_name_plural': '\u540c\u5fc3\u4e07\u70b9',
            },
        ),
        migrations.CreateModel(
            name='Txpad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlpad', models.CharField(max_length=50, null=True, verbose_name='\u70ed\u66f4\u5237\u65b0\u5730\u5740')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u70ed\u66f4\u5730\u5740',
                'verbose_name_plural': '\u70ed\u66f4\u5730\u5740',
            },
        ),
    ]
