# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-20 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('txnetworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='txpad',
            options={'ordering': ['id'], 'verbose_name': '\u70ed\u66f4\u5730\u5740URL', 'verbose_name_plural': '\u70ed\u66f4\u5730\u5740'},
        ),
    ]
