# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-27 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ali_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('ip', models.GenericIPAddressField(db_index=True, null=True, protocol='ipv4')),
                ('active', models.TextField()),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u963f\u91ccCdn',
                'verbose_name_plural': '\u963f\u91ccCdn',
            },
        ),
    ]
