# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-27 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ali_record',
            name='active',
            field=models.TextField(verbose_name='\u5237\u65b0\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='ali_record',
            name='date',
            field=models.CharField(max_length=32, verbose_name='\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='ali_record',
            name='ip',
            field=models.GenericIPAddressField(db_index=True, null=True, protocol='ipv4', verbose_name='IP\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='ali_record',
            name='username',
            field=models.CharField(max_length=32, verbose_name='\u7528\u6237'),
        ),
    ]
