# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-10 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='\u544a\u8b66\u7528\u6237')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='\u624b\u673a\u53f7')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u77ed\u4fe1\u544a\u8b66',
                'verbose_name_plural': '\u77ed\u4fe1\u544a\u8b66\u901a\u77e5',
            },
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=50, verbose_name='\u4e3b\u673a\u540d\u79f0')),
                ('message', models.CharField(blank=True, max_length=50, verbose_name='\u544a\u8b66\u4fe1\u606f')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='\u5f53\u524d\u72b6\u6001')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='\u544a\u8b66\u7ea7\u522b')),
                ('times', models.CharField(blank=True, max_length=50, verbose_name='\u544a\u8b66\u65f6\u95f4')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u544a\u8b66\u4fe1\u606f',
                'verbose_name_plural': '\u544a\u8b66\u4fe1\u606f\u5217\u8868',
            },
        ),
    ]
