# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-12 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d')),
                ('age', models.SmallIntegerField(verbose_name=b'\xe5\xb9\xb4\xe9\xbe\x84')),
                ('sex', models.SmallIntegerField(choices=[(1, b'\xe7\x94\xb7'), (2, b'\xe5\xa5\xb3'), (3, b'\xe6\x9c\xaa\xe7\x9f\xa5')], verbose_name=b'\xe6\x80\xa7\xe5\x88\xab')),
            ],
        ),
    ]
