# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-13 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
