# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-10 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graphs',
            fields=[
                ('graphid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '\u7ed8\u56fe',
                'verbose_name_plural': '\u7ed8\u56fe',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('groupid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('internal', models.IntegerField(default=0, null=True)),
                ('flags', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u7ec4',
                'verbose_name_plural': '\u4e3b\u673a\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('hostid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=128)),
                ('status', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('flags', models.IntegerField()),
                ('interfaces', models.GenericIPAddressField()),
                ('templatenum', models.IntegerField()),
                ('itemsnum', models.IntegerField()),
                ('triggernum', models.IntegerField()),
                ('graphsnum', models.IntegerField()),
                ('screensid', models.IntegerField()),
                ('applicationsnum', models.IntegerField()),
                ('groupid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zabbix.Groups')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u8868',
                'verbose_name_plural': '\u4e3b\u673a\u8868',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(db_column='key_', max_length=255)),
                ('delay', models.IntegerField()),
                ('history', models.IntegerField()),
                ('trends', models.IntegerField()),
                ('status', models.IntegerField()),
                ('lastclock', models.IntegerField()),
                ('data_type', models.IntegerField()),
                ('hostid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zabbix.Hosts')),
            ],
            options={
                'verbose_name': '\u76d1\u63a7\u9879',
                'verbose_name_plural': '\u76d1\u63a7\u9879',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('proxyid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('host', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': '\u4ee3\u7406',
                'verbose_name_plural': '\u4ee3\u7406',
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('templateid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': '\u6a21\u7248\u8868',
                'verbose_name_plural': '\u6a21\u7248\u8868',
            },
        ),
        migrations.CreateModel(
            name='Triggers',
            fields=[
                ('triggerid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('expression', models.CharField(max_length=2048)),
                ('description', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('comments', models.TextField()),
                ('templateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zabbix.Templates')),
            ],
            options={
                'verbose_name': '\u89e6\u53d1\u5668',
                'verbose_name_plural': '\u89e6\u53d1\u5668',
            },
        ),
        migrations.AddField(
            model_name='hosts',
            name='proxyid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zabbix.Proxy'),
        ),
        migrations.AddField(
            model_name='hosts',
            name='templateid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zabbix.Templates'),
        ),
    ]
