# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-27 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCMrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('active', models.TextField()),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u7f51\u5bbfCdn',
                'verbose_name_plural': '\u7f51\u5bbfCdn',
            },
        ),
    ]
