# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-27 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccmapp', '0003_ccmrecord_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ccmrecord',
            options={'ordering': ['id'], 'verbose_name': '\u7f51\u5bbfCdn', 'verbose_name_plural': '\u7f51\u5bbfCdn'},
        ),
    ]
