# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-09 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whitecloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=32, verbose_name='\u65f6\u95f4')),
                ('username', models.CharField(max_length=32, verbose_name='\u7528\u6237')),
                ('ip', models.GenericIPAddressField(db_index=True, null=True, protocol='ipv4', verbose_name='IP\u5730\u5740')),
                ('active', models.TextField(verbose_name='\u5237\u65b0\u5185\u5bb9')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u767d\u5c71\u4e91',
                'verbose_name_plural': '\u767d\u5c71\u4e91Cdn',
            },
        ),
    ]
