# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SHANXI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostId', models.IntegerField(max_length=7, verbose_name='\u4e3b\u673aId')),
                ('Hostname', models.CharField(max_length=30, verbose_name='\u4e3b\u673a\u540d\u79f0')),
                ('HostIp', models.GenericIPAddressField(protocol='ipv4', verbose_name='\u4e3b\u673aIP\u5730\u5740')),
                ('status', models.IntegerField(max_length=5, verbose_name='\u4e3b\u673a\u72b6\u6001')),
            ],
            options={
                'ordering': ['HostId'],
                'db_table': 'SHANXI',
                'verbose_name': '\u9655\u897f\u9ebb\u5c06',
                'verbose_name_plural': '\u9655\u897f\u9ebb\u5c06',
            },
        ),
    ]
