# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20171227_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SHANXI',
        ),
    ]
